# We wrote these commands in docker-compose.yml 

# Enable logical replication decoding — required for Debezium
wal_level = logical

# Maximum number of replication slots
# One slot per Debezium connector instance
max_replication_slots = 4

# Maximum number of WAL sender processes
max_wal_senders = 4

# How much WAL to keep on disk if a replica falls behind (MB)
# Prevents disk fill if Debezium is down for a while
wal_keep_size = 1024